spring:
  jpa:
    ddl-auto: create
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/universidad
    username: root
    password: toor
    hikari:
      connection-timeout:  60000
      maximum-pool-size: 5
